title: Data Science Portfolio
description: Documenting my learning in Data Science
theme: jekyll-theme-minimal
logo: profile.png
author: Monica Mawi
show_downloads: false
github:
  is_project_page: false
social_links:
  github: https://github.com/monicarem
  - https://monicarem.github.io/data-science-portfolio
  linkedin: https://www.linkedin.com/in/monica-mawi-738713283/
