title: Data Science Portfolio
description: Documenting my learning in Data Science
theme: jekyll-theme-minimal
logo: profile.png
author: Monica Mawi
show_downloads: false
github:
  is_project_page: false
  owner_url: https://github.com/monicarem
  owner_name: monicarem
linkedin_url: https://www.linkedin.com/in/monica-mawi-738713283/
